import { useState } from 'react'
import { PageLayout, LeftPanel } from '../components/PageLayout'
import NavBar from '../components/NavBar'
import RightPanel from '../components/RightPanel'
import ActionButton from '../components/ActionButton'
import PageTitle from '../components/PageTitle'
import './DataLogPage.css'

/**
 * Placeholder test run entries — will eventually be populated
 * from PDF files generated by the simulator.
 */
const TEST_RUNS = [
  { id: 1, label: 'Test Run I',   scenario: 'Scenario I',   date: '15 Mar 2026', households: 4, status: 'Completed' },
  { id: 2, label: 'Test Run II',  scenario: 'Scenario II',  date: '14 Mar 2026', households: 4, status: 'Completed' },
  { id: 3, label: 'Test Run III', scenario: 'Scenario I',   date: '13 Mar 2026', households: 3, status: 'Completed' },
  { id: 4, label: 'Test Run IV',  scenario: 'Scenario III', date: '12 Mar 2026', households: 4, status: 'Stopped' },
  { id: 5, label: 'Test Run V',   scenario: 'Scenario II',  date: '11 Mar 2026', households: 2, status: 'Completed' },
  { id: 6, label: 'Test Run VI',  scenario: 'Scenario IV',  date: '10 Mar 2026', households: 4, status: 'Completed' },
]

/**
 * DataLogPage — Browse previous simulation test runs.
 *
 * Features:
 *   - Click a card to select it for individual viewing
 *   - Drag cards into the two compare boxes to compare two runs
 *   - Forward arrow navigates to individual or comparison view
 *
 * Route: /datalog
 */
function DataLogPage() {
  const [selected, setSelected] = useState(null)
  const [compareA, setCompareA] = useState(null)
  const [compareB, setCompareB] = useState(null)

  const selectedRun = TEST_RUNS.find(r => r.id === selected)
  const compareRunA = TEST_RUNS.find(r => r.id === compareA)
  const compareRunB = TEST_RUNS.find(r => r.id === compareB)

  const bothCompareSet = compareA !== null && compareB !== null

  // Determine forward arrow destination
  const getForwardTo = () => {
    if (bothCompareSet) return `/datalog/compare/${compareA}/${compareB}`
    if (selected) return `/datalog/${selected}`
    return '/datalog'
  }

  const isForwardDisabled = selected === null && !bothCompareSet

  // Label for the forward button hover/tooltip
  const getForwardLabel = () => {
    if (bothCompareSet) return `Compare ${compareRunA?.label} vs ${compareRunB?.label}`
    if (selected) return `Summary ${selectedRun?.label}`
    return ''
  }

  // --- Drag handlers ---
  const handleDragStart = (e, runId) => {
    e.dataTransfer.setData('text/plain', String(runId))
    e.dataTransfer.effectAllowed = 'copy'
  }

  const handleDragOver = (e) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = 'copy'
  }

  const handleDropA = (e) => {
    e.preventDefault()
    const runId = Number(e.dataTransfer.getData('text/plain'))
    if (runId && runId !== compareB) {
      setCompareA(runId)
    }
  }

  const handleDropB = (e) => {
    e.preventDefault()
    const runId = Number(e.dataTransfer.getData('text/plain'))
    if (runId && runId !== compareA) {
      setCompareB(runId)
    }
  }

  // Clear a compare box on click
  const clearCompareA = () => setCompareA(null)
  const clearCompareB = () => setCompareB(null)

  return (
    <PageLayout variant="sidebar">
      <LeftPanel scrollable compact>
        <NavBar backTo="/" />
        <PageTitle>Data Log --</PageTitle>
        <div className="datalog__grid">
          {TEST_RUNS.map(run => (
            <button
              key={run.id}
              type="button"
              className={`datalog__card${selected === run.id ? ' datalog__card--selected' : ''}`}
              onClick={() => setSelected(run.id)}
              draggable
              onDragStart={(e) => handleDragStart(e, run.id)}
            >
              <span className="datalog__card-label">{run.label}</span>
            </button>
          ))}
        </div>
      </LeftPanel>
      <RightPanel variant="action" color="gray" compact>
        {/* Selected run info */}
        {selectedRun && (
          <div className="datalog__sidebar-summary">
            <h3 className="datalog__sidebar-title">{selectedRun.label}</h3>
            <ul className="datalog__sidebar-list">
              <li>Scenario: {selectedRun.scenario}</li>
              <li>Date: {selectedRun.date}</li>
              <li>Households: {selectedRun.households}</li>
              <li>Status: {selectedRun.status}</li>
            </ul>
          </div>
        )}

        {/* Compare section */}
        <div className="datalog__compare">
          <h4 className="datalog__compare-title">Compare Tests</h4>
          <div className="datalog__compare-boxes">
            <div
              className={`datalog__compare-box${compareA ? ' datalog__compare-box--filled' : ''}`}
              onDragOver={handleDragOver}
              onDrop={handleDropA}
              onClick={compareA ? clearCompareA : undefined}
              title={compareA ? `${compareRunA?.label} (click to clear)` : 'Drag a test run here'}
            >
              {compareA ? (
                <span className="datalog__compare-box-label">{compareRunA?.label}</span>
              ) : null}
            </div>
            <span className="datalog__compare-plus">+</span>
            <div
              className={`datalog__compare-box${compareB ? ' datalog__compare-box--filled' : ''}`}
              onDragOver={handleDragOver}
              onDrop={handleDropB}
              onClick={compareB ? clearCompareB : undefined}
              title={compareB ? `${compareRunB?.label} (click to clear)` : 'Drag a test run here'}
            >
              {compareB ? (
                <span className="datalog__compare-box-label">{compareRunB?.label}</span>
              ) : null}
            </div>
          </div>
        </div>

        <div className="datalog__forward-wrapper" title={getForwardLabel()}>
          <ActionButton
            type="forward"
            to={getForwardTo()}
            disabled={isForwardDisabled}
            label={isForwardDisabled ? '' : getForwardLabel()}
          />
        </div>
      </RightPanel>
    </PageLayout>
  )
}

export default DataLogPage
