import { useParams } from 'react-router-dom'
import { PageLayout, LeftPanel } from '../components/PageLayout'
import NavBar from '../components/NavBar'
import RightPanel from '../components/RightPanel'
import PageTitle from '../components/PageTitle'
import './DataLogComparePage.css'

/**
 * DataLogComparePage — Side-by-side comparison of two test runs.
 *
 * Will eventually display a comparison PDF generated by the simulator.
 * For now shows placeholder content for both runs.
 *
 * Route: /datalog/compare/:runIdA/:runIdB
 */
function DataLogComparePage() {
  const { runIdA, runIdB } = useParams()

  const handleDownload = () => {
    alert(`Download comparison PDF: Test Run ${runIdA} vs ${runIdB} (not yet connected)`)
  }

  return (
    <PageLayout variant="sidebar">
      <LeftPanel scrollable compact>
        <NavBar backTo="/datalog" />
        <PageTitle>Compare: Run {runIdA} vs Run {runIdB} --</PageTitle>

        <div className="datalog-compare__content">
          <div className="datalog-compare__section">
            <h2 className="datalog-compare__heading">Performance Comparison</h2>
            <div className="datalog-compare__placeholder datalog-compare__placeholder--wide">
              Side-by-side performance metrics placeholder.
            </div>
          </div>

          <div className="datalog-compare__section">
            <h2 className="datalog-compare__heading">Grid Load Comparison</h2>
            <div className="datalog-compare__placeholder datalog-compare__placeholder--wide">
              Comparative grid load charts placeholder.
            </div>
          </div>

          <div className="datalog-compare__section">
            <h2 className="datalog-compare__heading">Household Outcomes</h2>
            <div className="datalog-compare__placeholder datalog-compare__placeholder--wide">
              Household-level comparison table placeholder.
            </div>
          </div>

          <div className="datalog-compare__section">
            <h2 className="datalog-compare__heading">Key Differences</h2>
            <div className="datalog-compare__placeholder datalog-compare__placeholder--tall">
              Summary of key differences between runs placeholder.
            </div>
          </div>
        </div>
      </LeftPanel>
      <RightPanel variant="action" color="gray" compact>
        <div className="datalog-compare__download-wrapper">
          <button
            className="datalog-compare__download-btn"
            onClick={handleDownload}
            aria-label="Download comparison PDF"
          >
            <span className="datalog-compare__download-icon">&darr;</span>
          </button>
          <span className="datalog-compare__download-label">Download</span>
        </div>
      </RightPanel>
    </PageLayout>
  )
}

export default DataLogComparePage
